# Cargar el módulo ModSecurity globalmente
load_module /etc/nginx/modules/ngx_http_modsecurity_module.so;

# Directiva user en el contexto global
user www-data;
worker_processes  1;

events {
        worker_connections 1024;
    }

http {

    include       mime.types;
    default_type  application/octet-stream;

    # Habilitar ModSecurity globalmente
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/modsecurity.conf;
    modsecurity_rules_file /etc/nginx/modsec/crs-setup.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-901-INITIALIZATION.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-905-COMMON-EXCEPTIONS.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-911-METHOD-ENFORCEMENT.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-913-SCANNER-DETECTION.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-921-PROTOCOL-ATTACK.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-922-MULTIPART-ATTACK.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/REQUEST-949-BLOCKING-EVALUATION.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-950-DATA-LEAKAGES.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-955-WEB-SHELLS.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-959-BLOCKING-EVALUATION.conf;
    modsecurity_rules_file /etc/nginx/modsec/rules/RESPONSE-980-CORRELATION.conf;

    modsecurity_transaction_id "default-$request_id";

    server {
        include /etc/nginx/sites-enabled/default;
    }
}