[paths]
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins

[server]
protocol = https
http_port = 3000
domain = localhost
root_url = https://localhost:3003/
cert_file = /etc/grafana/ssl/grafana.crt
cert_key = /etc/grafana/ssl/grafana.key
enforce_domain = false

[dataproxy]
timeout = 120
dial_timeout = 30
keep_alive_seconds = 60

[database]
type = sqlite3
path = /var/lib/grafana/grafana.db
cache_mode = private
max_idle_conn = 5
max_open_conn = 20
busy_timeout = 50000

[analytics]
check_for_updates = true

[security]
admin_user = admin
# admin_password se establecerá por variable de entorno
disable_gravatar = true
cookie_secure = true
cookie_samesite = strict
secret_key = ${GENERATED_SECRET} 

[auth.anonymous]
enabled = false

[auth.basic]
enabled = true

[plugins]
allow_loading_unsigned_plugins = grafana-exploretraces-app,grafana-metricsdrilldown-app,grafana-lokiexplore-app,grafana-pyroscope-app
allow_loading_unsafe_plugins = grafana-simple-json-datasource