SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On 
SecDataDir /var/cache/modsecurity/
SecTmpDir /tmp/modsecurity/
SecAuditLog /var/log/modsec/modsec_audit.log
SecDebugLog /var/log/modsec/modsec_debug.log
SecDebugLogLevel 9
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLogStorageDir /var/log/modsec/
SecRule ARGS|REQUEST_HEADERS "@detectXSS" "id:1001,deny,status:403,msg:'XSS Attack Detected'"
SecRule REQUEST_URI|REQUEST_BODY "@contains ../" "id:1002,phase:1,deny,status:403,msg:'Path Traversal Attack Detected',t:none,t:urlDecode,t:normalizePathWin,t:normalizePath"
SecDefaultAction "phase:1,log,auditlog,deny,status:403"
SecComponentSignature "OWASP_CRS"

# Excepción para actualización de color de avatar
#SecRule REQUEST_URI "@streq /api/profile" \
    "id:1006,phase:1,pass,nolog,\
    ctl:ruleRemoveById=932100-932199,\
    ctl:ruleRemoveById=941100-941199"

# Excepción para parámetro de color
SecRule &ARGS_NAMES "@contains favourite_color" \
    "id:1007,phase:2,pass,nolog,\
    ctl:ruleRemoveById=932130,\
    ctl:ruleRemoveById=941160"

# Excepciones para entorno local
SecRule SERVER_ADDR "@streq 127.0.0.1" \
    "id:1003,phase:1,pass,nolog,\
    ctl:ruleRemoveById=920350,\
    ctl:ruleRemoveById=941100-941199,\
    ctl:ruleRemoveById=932100-932199"

SecRule REQUEST_HEADERS:Origin "@streq https://localhost:8443" \
    "id:1004,phase:1,pass,nolog,\
    ctl:ruleRemoveById=920340"

# Permitir PUT en /backend/
SecRule REQUEST_URI "@beginsWith /backend/" \
    "id:1008,phase:1,pass,nolog,\
     ctl:ruleRemoveById=911100"